<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <AssemblyVersion>0.90.19</AssemblyVersion>
    <VersionRevision>30</VersionRevision>
    <BinaryVersionRevision>$(VersionRevision)</BinaryVersionRevision>
    <AssemblyProduct>AnyFSE</AssemblyProduct>
    <AssemblyCompany>Artem Shpynov</AssemblyCompany>
    <BinarySigningCN>Artem Shpynov</BinarySigningCN>
    <AssemblyDescription>AnyFSE Home application launcher</AssemblyDescription>
    <AssemblyCopyright>Copyright © 2026 Artem Shpynov. All rights reserved.</AssemblyCopyright>
    <AssemblyInternalName>$(TargetName)</AssemblyInternalName>
    <PublisherCN>DDCC7751-898D-4BC9-B80C-4AA73E5D5762</PublisherCN>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ResourceCompile>
      <PreprocessorDefinitions>
                VER_VERSION=$(AssemblyVersion.Replace('.', ',')),$(BinaryVersionRevision);
                VER_VERSION_STR=\"$(AssemblyVersion)\";
                COMPANY_NAME=\"$(AssemblyCompany)\";
                PRODUCT_NAME=\"$(AssemblyProduct)\";
                FILE_DESCRIPTION=\"$(AssemblyDescription)\";
                INTERNAL_NAME=\"$(AssemblyInternalName)\";
                LEGAL_COPYRIGHT=\"$(AssemblyCopyright)\";
                ORIGINAL_FILENAME=\"$(TargetName)$(TargetExt)\";
                %(PreprocessorDefinitions)
            </PreprocessorDefinitions>
    </ResourceCompile>
  </ItemDefinitionGroup>
</Project>